rm(list=ls())
library(clusterProfiler)
library(GSEABase)
setwd("~/Documents/4Fun/TranscriptoShiny/DEGAnalysis")
c2.cp.biocarta<-getGmt("../Msigdb/c2.cp.biocarta.v2024.1.Hs.symbols.gmt")
c2.cp.kegg_legacy<-getGmt("../Msigdb/c2.cp.kegg_legacy.v2024.1.Hs.symbols.gmt")
c2.cp.kegg_medicus<-getGmt("../Msigdb/c2.cp.kegg_medicus.v2024.1.Hs.symbols.gmt")
c2.cp.pid<-getGmt("../Msigdb/c2.cp.pid.v2024.1.Hs.symbols.gmt")
c2.cp.wikipathways<-getGmt("../Msigdb/c2.cp.wikipathways.v2024.1.Hs.symbols.gmt")
h.all<-getGmt("../Msigdb/h.all.v2024.1.Hs.symbols.gmt")
c6.all<-getGmt("../Msigdb/c6.all.v2024.1.Hs.symbols.gmt")
c8.all<-getGmt("../Msigdb/c8.all.v2024.1.Hs.symbols.gmt")


Sys.setenv(http_proxy = "http://127.0.0.1:7890")
Sys.setenv(https_proxy = "http://127.0.0.1:7890")
library(decoupleR)
progenyNet.mouse <- get_progeny(organism = 'mouse', top = 500)
progenyNet.human <- get_progeny(organism = 'human', top = 500)
collectriNet.mouse <- get_collectri(organism = 'mouse', split_complexes=FALSE)
collectriNet.human <- get_collectri(organism = 'human', split_complexes=FALSE)


save(c2.cp.biocarta,c2.cp.kegg_legacy,c2.cp.kegg_medicus,c2.cp.pid,c2.cp.wikipathways,h.all,c6.all,progenyNet.mouse,progenyNet.human,collectriNet.mouse,collectriNet.human,c8.all,file="AnnoPwDBsV2.RData")

setwd("~/Documents/4Fun/TranscriptoShiny/DEGAnalysis")
rm(list=ls())
library(gson)
c2.cp.biocarta<-read.gmt("../Msigdb/c2.cp.biocarta.v2024.1.Hs.symbols.gmt")
c2.cp.kegg_legacy<-read.gmt("../Msigdb/c2.cp.kegg_legacy.v2024.1.Hs.symbols.gmt")
c2.cp.kegg_medicus<-read.gmt("../Msigdb/c2.cp.kegg_medicus.v2024.1.Hs.symbols.gmt")
c2.cp.pid<-read.gmt("../Msigdb/c2.cp.pid.v2024.1.Hs.symbols.gmt")
c2.cp.wikipathways<-read.gmt("../Msigdb/c2.cp.wikipathways.v2024.1.Hs.symbols.gmt")
h.all<-read.gmt("../Msigdb/h.all.v2024.1.Hs.symbols.gmt")
c6.all<-read.gmt("../Msigdb/c6.all.v2024.1.Hs.symbols.gmt")
c8.all<-read.gmt("../Msigdb/c8.all.v2024.1.Hs.symbols.gmt")
MKEGGgson<-read.gson("./MKEGG_human.gson")
KEGGgson<-read.gson("./MKEGG_human.gson")
library(data.table)
PanglaoDB_markers_27_Mar_2020<-fread("../Msigdb/PanglaoDB_markers_27_Mar_2020.tsv.gz")
PanglaoDBT2G<-PanglaoDB_markers_27_Mar_2020%>%dplyr::select(`cell type`,`official gene symbol`)
colnames(PanglaoDBT2G)[1:2]<-c("term","gene")
db.pldf<-PanglaoDBT2G
save(c2.cp.biocarta,c2.cp.kegg_legacy,c2.cp.kegg_medicus,c2.cp.pid,c2.cp.wikipathways,h.all,c6.all,c8.all,MKEGGgson,KEGGgson,db.pldf,file="AnnoPwDBsV2_4CP.RData")
